apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  environment: dev
namePrefix: dev-

resources:
  - ../../base

patchesStrategicMerge:
  - patch.yaml

# configMapGenerator:
#   - name: us-config
#     envs:
#       - user-service/config/config.properties
#   - name: gateway-config
#     envs:
#       - api-gateway/config/config.properties

# secretGenerator:
#   - name: us-secrets
#     envs:
#       - user-service/config/secret.properties
