apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-demo-by-go
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://gitlab.opencanvasatelier.com/com001/infrastructure/aws/manifest.git
    targetRevision: master
    path: overlays/dev
    # path: sample

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
